"use client"
import { useState, useEffect } from 'react'
import { useRouter, useParams } from 'next/navigation'
import { z } from 'zod'
import { useForm, useFieldArray } from 'react-hook-form'
import { zodResolver } from '@hookform/resolvers/zod'
import { apiFetch } from '@/lib/api/client'
import { Button } from '@/components/ui/button'
import { Input } from '@/components/ui/input'
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card'
import { Form, FormField, FormItem, FormLabel, FormControl, FormMessage } from '@/components/ui/form'
import { Select, SelectTrigger, SelectValue, SelectContent, SelectItem } from '@/components/ui/select'
import Link from 'next/link'
import { Plus, Trash2, ArrowLeft, Loader2 } from 'lucide-react'
import { toast } from 'sonner'

const itemSchema = z.object({
  barang_id: z.string().min(1),
  jumlah: z.coerce.number().int().positive(),
  harga_satuan: z.coerce.number().nonnegative(),
  keterangan: z.string().optional(),
})

const schema = z.object({
  status: z.string().optional(),
  di_id: z.string().optional(),
  items: z.array(itemSchema).min(1),
})

type FV = z.input<typeof schema>

const statusOpts = [
  { value: 'draft', label: 'Draft' },
  { value: 'confirmed', label: 'Dikonfirmasi' },
  { value: 'processed', label: 'Diproses' },
  { value: 'delivered', label: 'Dikirim' },
]

export default function EditSoPage() {
  const router = useRouter()
  const params = useParams()
  const id = params.id as string
  const [loading, setLoading] = useState(true)
  const [submitting, setSubmitting] = useState(false)
  const [barangOpts, setBarangOpts] = useState<Array<{ value: string; label: string }>>([])
  const [diOpts, setDiOpts] = useState<Array<{ value: string; label: string }>>([])
  const [diLoading, setDiLoading] = useState(false)
  const [currentDiId, setCurrentDiId] = useState<string>('')

  const form = useForm<FV>({ resolver: zodResolver(schema) })
  const { register, handleSubmit, control, reset, setValue } = form
  const { fields, append, remove } = useFieldArray({ control, name: 'items' })

  useEffect(() => {
    Promise.all([
      apiFetch<Array<{ id: string; nama: string; kode: string }>>('/api/v1/master/barang'),
      apiFetch<Array<Record<string, unknown>>>('/api/v1/di'),
    ]).then(([b, diList]) => {
      setBarangOpts((b.data ?? []).map(x => ({ value: x.id, label: `[${x.kode}] ${x.nama}` })))
      const activeDi = (diList.data ?? []).filter((d: Record<string, unknown>) => d.status === 'active')
      setDiOpts(activeDi.map((d: Record<string, unknown>) => {
        const customer = d.customer as Record<string, unknown> ?? {}
        return { value: d.id as string, label: `${d.nomor as string} — ${customer.nama as string ?? '-'}` }
      }))
    }).catch(() => toast.error('Gagal memuat data'))
  }, [])

  useEffect(() => {
    apiFetch<{ status: string; di_id: string | null; items: Array<{ barang_id: string; jumlah: number; harga_satuan: number; keterangan?: string }> }>(`/api/v1/sales-order/${id}`)
      .then((r) => {
        const d = r.data
        setCurrentDiId(d.di_id ?? '')
        reset({
          status: d.status,
          di_id: d.di_id ?? '',
          items: d.items.length > 0
            ? d.items.map(i => ({ barang_id: i.barang_id, jumlah: i.jumlah, harga_satuan: i.harga_satuan, keterangan: i.keterangan ?? '' }))
            : [{ barang_id: '', jumlah: 1, harga_satuan: 0 }],
        })
        setLoading(false)
      })
      .catch(() => { toast.error('Gagal memuat SO'); router.push('/dashboard/sales-order') })
  }, [id, reset, router])

  const handleDiSelect = async (diId: string) => {
    setValue('di_id', diId)
    if (!diId) return
    setDiLoading(true)
    try {
      const diRes = await apiFetch<Record<string, unknown>>(`/api/v1/di/${diId}`)
      const diData = diRes.data
      const diItems = (diData.items as Array<Record<string, unknown>>) ?? []
      const kontrakId = diData.kontrak_id as string | null

      const hargaMap = new Map<string, number>()
      if (kontrakId) {
        try {
          const kontrakRes = await apiFetch<Record<string, unknown>>(`/api/v1/master/kontrak/${kontrakId}`)
          const kontrakItems = (kontrakRes.data?.items as Array<Record<string, unknown>>) ?? []
          for (const ki of kontrakItems) {
            hargaMap.set(ki.barang_id as string, ki.harga_satuan as number)
          }
        } catch {}
      }

      reset({
        status: form.getValues('status'),
        di_id: diId,
        items: diItems.map(i => ({
          barang_id: i.barang_id as string,
          jumlah: i.jumlah as number,
          harga_satuan: hargaMap.get(i.barang_id as string) ?? 0,
          keterangan: (i.keterangan as string) ?? '',
        })),
      })
    } catch {
      toast.error('Gagal memuat data DI')
    } finally {
      setDiLoading(false)
    }
  }

  const onSubmit = async (data: FV) => {
    setSubmitting(true)
    try {
      const res = await apiFetch<{ autoGenerated?: { id: string; nomor: string; type: string } }>(
        `/api/v1/sales-order/${id}`,
        { method: 'PUT', body: JSON.stringify(data) }
      )
      const autoGenerated = res.data?.autoGenerated
      if (autoGenerated) {
        toast.success('SO diupdate!', {
          description: `Delivery Order ${autoGenerated.nomor} otomatis dibuat`,
          action: { label: 'Lihat DO', onClick: () => router.push(`/dashboard/delivery-order/${autoGenerated.id}`) },
        })
        return
      }
      toast.success('SO berhasil diupdate!')
      router.push('/dashboard/sales-order')
    } catch (err) {
      toast.error(err instanceof Error ? err.message : 'Terjadi kesalahan')
    } finally {
      setSubmitting(false)
    }
  }

  if (loading) return <div className="flex justify-center py-12"><Loader2 className="h-6 w-6 animate-spin" /></div>

  return (
    <div className="max-w-3xl space-y-6">
      <div className="flex items-center gap-4">
        <Button variant="ghost" size="icon" asChild><Link href="/dashboard/sales-order"><ArrowLeft className="h-5 w-5" /></Link></Button>
        <div><h1 className="text-3xl font-heading font-bold">Edit SO</h1></div>
      </div>

      <Form {...form}>
        <form onSubmit={handleSubmit(onSubmit)} className="space-y-6">
          <Card>
            <CardHeader><CardTitle className="text-base">Informasi SO</CardTitle></CardHeader>
            <CardContent className="space-y-4">
              <div className="grid grid-cols-2 gap-4">
                <FormField control={control} name="status" render={({ field }) => (
                  <FormItem><FormLabel>Status</FormLabel>
                    <Select onValueChange={field.onChange} value={field.value}>
                      <FormControl><SelectTrigger><SelectValue placeholder="Pilih status" /></SelectTrigger></FormControl>
                      <SelectContent>{statusOpts.map(o => <SelectItem key={o.value} value={o.value}>{o.label}</SelectItem>)}</SelectContent>
                    </Select>
                    <FormMessage />
                  </FormItem>
                )} />
                <FormField control={control} name="di_id" render={({ field }) => (
                  <FormItem><FormLabel>DI Reference</FormLabel>
                    <Select onValueChange={(v) => { field.onChange(v); handleDiSelect(v) }} value={field.value}>
                      <FormControl><SelectTrigger><SelectValue placeholder={currentDiId ? 'Ganti DI (opsional)' : 'Pilih DI (opsional)'} /></SelectTrigger></FormControl>
                      <SelectContent>
                        <SelectItem value="">{currentDiId ? 'Hapus referensi DI' : 'Tidak ada DI'}</SelectItem>
                        {diOpts.map(o => <SelectItem key={o.value} value={o.value}>{o.label}</SelectItem>)}
                      </SelectContent>
                    </Select>
                    <FormMessage />
                  </FormItem>
                )} />
              </div>
              {diLoading && <div className="flex justify-center py-2"><Loader2 className="h-4 w-4 animate-spin" /></div>}
            </CardContent>
          </Card>

          <Card>
            <CardHeader className="flex flex-row items-center justify-between">
              <CardTitle className="text-base">Item Barang</CardTitle>
              <Button type="button" variant="outline" size="sm" onClick={() => append({ barang_id: '', jumlah: 1, harga_satuan: 0, keterangan: '' })}>
                <Plus className="h-4 w-4 mr-1" />Tambah
              </Button>
            </CardHeader>
            <CardContent className="space-y-4">
              {fields.map((f, i) => (
                <div key={f.id} className="p-4 border rounded-lg space-y-3">
                  <div className="flex items-center justify-between">
                    <span className="text-sm text-muted-foreground">Item #{i + 1}</span>
                    {fields.length > 1 && (
                      <Button type="button" variant="ghost" size="sm" onClick={() => remove(i)}>
                        <Trash2 className="h-4 w-4 text-destructive" />
                      </Button>
                    )}
                  </div>
                  <div className="grid grid-cols-3 gap-3">
                    <FormField control={control} name={`items.${i}.barang_id`} render={({ field }) => (
                      <FormItem><FormLabel>Barang *</FormLabel>
                        <Select onValueChange={field.onChange} value={field.value}>
                          <FormControl><SelectTrigger><SelectValue placeholder="Pilih" /></SelectTrigger></FormControl>
                          <SelectContent>{barangOpts.map(o => <SelectItem key={o.value} value={o.value}>{o.label}</SelectItem>)}</SelectContent>
                        </Select>
                        <FormMessage />
                      </FormItem>
                    )} />
                    <div className="space-y-2">
                      <label className="text-xs font-medium">Jumlah *</label>
                      <Input type="number" min="1" {...register(`items.${i}.jumlah`)} />
                    </div>
                    <div className="space-y-2">
                      <label className="text-xs font-medium">Harga *</label>
                      <Input type="number" min="0" {...register(`items.${i}.harga_satuan`)} />
                    </div>
                  </div>
                  <div className="space-y-2">
                    <label className="text-xs font-medium">Keterangan</label>
                    <Input {...register(`items.${i}.keterangan`)} />
                  </div>
                </div>
              ))}
            </CardContent>
          </Card>

          <div className="flex justify-end gap-3">
            <Button type="button" variant="cancel"><Link href="/dashboard/sales-order">Batal</Link></Button>
            <Button type="submit" disabled={submitting}>
              {submitting && <Loader2 className="h-4 w-4 mr-2 animate-spin" />}
              {submitting ? '...' : 'Update'}
            </Button>
          </div>
        </form>
      </Form>
    </div>
  )
}
