"use client"
import { useState, useEffect } from 'react'; import { useRouter, useParams } from 'next/navigation'; import { z } from 'zod'; import { useForm } from 'react-hook-form'; import { zodResolver } from '@hookform/resolvers/zod'
import { apiFetch } from '@/lib/api/client'; import { Button } from '@/components/ui/button'; import { Card, CardContent } from '@/components/ui/card'
import Link from 'next/link'; import { ArrowLeft, Loader2 } from 'lucide-react'; import { toast } from 'sonner'

const schema = z.object({ status: z.string().optional() })
type FV = z.input<typeof schema>
const statusOpts = [{ value: 'draft', label: 'Draft' }, { value: 'confirmed', label: 'Dikonfirmasi' }, { value: 'processed', label: 'Diproses' }, { value: 'delivered', label: 'Dikirim' }]

export default function EditSoPage() {
  const router = useRouter(); const params = useParams(); const [loading, setLoading] = useState(true); const [submitting, setSubmitting] = useState(false)
  const { register, handleSubmit, reset } = useForm<FV>({ resolver: zodResolver(schema) })
  useEffect(() => {
    apiFetch<{ status: string }>(`/api/v1/sales-order/${params.id}`).then(r => { reset({ status: r.data.status }); setLoading(false) }).catch(() => { toast.error('Gagal'); router.push('/dashboard/sales-order') })
  }, [params.id, reset, router])
  const onSubmit = async (data: FV) => {
    setSubmitting(true); try {
      const res = await apiFetch(`/api/v1/sales-order/${params.id}`, { method: 'PUT', body: JSON.stringify(data) })
      const autoGenerated = (res as { autoGenerated?: { id: string; nomor: string; type: string } }).autoGenerated
      if (autoGenerated) {
        toast.success('SO diupdate!', { description: `Delivery Order ${autoGenerated.nomor} otomatis dibuat`, action: { label: 'Lihat DO', onClick: () => router.push(`/dashboard/delivery-order/${autoGenerated.id}`) } })
        return
      }
      toast.success('Diupdate!'); router.push('/dashboard/sales-order')
    }
    catch (err) { toast.error(err instanceof Error ? err.message : 'Error') } finally { setSubmitting(false) }
  }
  if (loading) return <div className="flex justify-center py-12"><Loader2 className="h-6 w-6 animate-spin" /></div>
  return (
    <div className="max-w-xl space-y-6">
      <div className="flex items-center gap-4"><Button variant="ghost" size="icon" asChild><Link href="/dashboard/sales-order"><ArrowLeft className="h-5 w-5" /></Link></Button><div><h1 className="text-3xl font-heading font-bold">Edit SO</h1></div></div>
      <form onSubmit={handleSubmit(onSubmit)} className="space-y-6">
        <Card><CardContent className="space-y-4 pt-6">
          <div className="space-y-2"><label className="text-sm font-medium">Status</label>
            <select {...register('status')} className="flex h-10 w-full rounded-md border border-input bg-background px-3 py-2 text-sm ring-offset-background focus-visible:outline-none focus-visible:ring-3 focus-visible:ring-ring">{statusOpts.map(o => <option key={o.value} value={o.value}>{o.label}</option>)}</select></div>
        </CardContent></Card>
        <div className="flex justify-end gap-3"><Button type="button" variant="outline" asChild><Link href="/dashboard/sales-order">Batal</Link></Button><Button type="submit" disabled={submitting}>{submitting ? '...' : 'Update'}</Button></div>
      </form>
    </div>
  )
}
