"use strict";
// Simple TypeScript types for database tables
// Generated by opencode

import { InferSelectModel, InferInsertModel } from 'drizzle-orm';
import { users } from '@/lib/db/schema/users';
import { userRoles } from '@/lib/db/schema/user-roles';
import { barang } from '@/lib/db/schema/barang';
import { kategoriBarang } from '@/lib/db/schema/kategori-barang';
import { supplier } from '@/lib/db/schema/supplier';
import { customer } from '@/lib/db/schema/customer';
import { karyawan } from '@/lib/db/schema/karyawan';
import { jabatan } from '@/lib/db/schema/jabatan';
import { coa } from '@/lib/db/schema/coa';
import { kontrak } from '@/lib/db/schema/kontrak';
import { invoice } from '@/lib/db/schema/invoice';
import { invoiceItem } from '@/lib/db/schema/invoice-item';

// Export basic types for common tables
export type User = InferSelectModel<typeof users>;
export type NewUser = InferInsertModel<typeof users>;
export type UserRole = InferSelectModel<typeof userRoles>;
export type NewUserRole = InferInsertModel<typeof userRoles>;

export type Barang = InferSelectModel<typeof barang>;
export type NewBarang = InferInsertModel<typeof barang>;

export type KategoriBarang = InferSelectModel<typeof kategoriBarang>;
export type NewKategoriBarang = InferInsertModel<typeof kategoriBarang>;

export type Supplier = InferSelectModel<typeof supplier>;
export type NewSupplier = InferInsertModel<typeof supplier>;

export type Customer = InferSelectModel<typeof customer>;
export type NewCustomer = InferInsertModel<typeof customer>;

export type Karyawan = InferSelectModel<typeof karyawan>;
export type NewKaryawan = InferInsertModel<typeof karyawan>;

export type Jabatan = InferSelectModel<typeof jabatan>;
export type NewJabatan = InferInsertModel<typeof jabatan>;

export type Coa = InferSelectModel<typeof coa>;
export type NewCoa = InferInsertModel<typeof coa>;

export type Kontrak = InferSelectModel<typeof kontrak>;
export type NewKontrak = InferInsertModel<typeof kontrak>;

export type Invoice = InferSelectModel<typeof invoice>;
export type NewInvoice = InferInsertModel<typeof invoice>;

export type InvoiceItem = InferSelectModel<typeof invoiceItem>;
export type NewInvoiceItem = InferInsertModel<typeof invoiceItem>;