"use client"

import { useState, useEffect } from "react"
import { useRouter, usePathname } from "next/navigation"
import { apiFetch } from "@/lib/api/client"
import { Button } from "@/components/ui/button"
import { Badge } from "@/components/ui/badge"
import { Card, CardContent } from "@/components/ui/card"
import { Table, TableHeader, TableBody, TableRow, TableHead, TableCell } from "@/components/ui/table"
import Link from "next/link"
import { ArrowLeft, FileText, CheckCircle, Loader2, ExternalLink, AlertTriangle, CheckCircle2 } from "lucide-react"
import { CompactFileUpload, type DocumentFile } from "@/components/compact-file-upload"
import { toast } from "sonner"

const s: Record<string, { label: string; v: "secondary" | "warning" | "success" | "outline" }> = {
  draft: { label: "Draft", v: "secondary" }, confirmed: { label: "Dikonfirmasi", v: "success" }, cancelled: { label: "Batal", v: "outline" },
}

interface CustomerPo {
  id: string
  nomor: string
  customer_id: string
  tanggal: string
  status: string
  nomor_po_customer: string | null
  terms_of_payment: string | null
  waktu_pengiriman: number | null
  pic_customer_id: string | null
  customer_pic: { nama: string; jabatan: string | null; no_hp: string | null } | null
  customer: { nama: string; kode: string } | null
  sales_order: { id: string; nomor: string; status: string } | null
  items: Array<{
    id: string
    jumlah: number
    harga_satuan: number
    barang: { nama: string; kode: string; satuan: string; image_url: string | null } | null
  }>
}

export default function CustomerPoDetailPage() {
  const router = useRouter()
  const pathname = usePathname()
  const id = pathname.split("/").pop()
  const [po, setPo] = useState<CustomerPo | null>(null)
  const [loading, setLoading] = useState(true)
  const [error, setError] = useState<string | null>(null)
  const [documents, setDocuments] = useState<DocumentFile[]>([])
  const [uploading, setUploading] = useState(false)
  const [statusLoading, setStatusLoading] = useState(false)

  const handleStatusChange = async (newStatus: string) => {
    if (!id) return
    setStatusLoading(true)
    try {
      const putRes = await apiFetch<{ autoGenerated?: { id: string; nomor: string; type: string } }>(`/api/v1/customer-po/${id}`, {
        method: 'PUT',
        body: JSON.stringify({ status: newStatus }),
      })
      if (putRes.data?.autoGenerated) {
        toast.success(`PO dikonfirmasi! ${putRes.data.autoGenerated.nomor} telah dibuat.`)
      } else {
        toast.success(`PO berhasil ${newStatus === 'confirmed' ? 'dikonfirmasi' : 'dibatalkan'}!`)
      }
      const res = await apiFetch<CustomerPo>(`/api/v1/customer-po/${id}`)
      setPo(res.data)
    } catch (err) {
      toast.error(err instanceof Error ? err.message : 'Gagal mengubah status')
    } finally {
      setStatusLoading(false)
    }
  }

  useEffect(() => {
    if (!id) return
    Promise.all([
      apiFetch<CustomerPo>(`/api/v1/customer-po/${id}`),
      apiFetch<DocumentFile[]>(`/api/v1/customer-po/${id}/documents`),
    ]).then(([poRes, docRes]) => {
      setPo(poRes.data)
      setDocuments(docRes.data ?? [])
      setLoading(false)
    }).catch((err) => {
      setError(err.message)
      setLoading(false)
    })
  }, [id])

  const handleUpload = async (file: File) => {
    if (!id) return
    setUploading(true)
    try {
      const formData = new FormData()
      formData.append("file", file)
      const { apiFetchFormData } = await import("@/lib/api/client")
      const r = await apiFetchFormData(`/api/v1/customer-po/${id}/documents`, formData)
      setDocuments((prev) => [r.data as DocumentFile, ...prev].filter(Boolean))
      toast.success("File berhasil diupload")
    } catch (err) {
      toast.error(err instanceof Error ? err.message : "Gagal upload file")
    } finally {
      setUploading(false)
    }
  }

  const handleDeleteDocument = async (docId: string) => {
    if (!id) return
    try {
      await apiFetch(`/api/v1/customer-po/${id}/documents?docId=${docId}`, { method: "DELETE" })
      setDocuments((prev) => prev.filter((d) => d.id !== docId))
      toast.success("File berhasil dihapus")
    } catch (err) {
      toast.error(err instanceof Error ? err.message : "Gagal hapus file")
    }
  }

  const dueDate = po?.waktu_pengiriman && po?.tanggal
    ? (() => { const d = new Date(po.tanggal); d.setDate(d.getDate() + po.waktu_pengiriman!); return d; })()
    : null
  const daysUntilDue = dueDate
    ? Math.ceil((dueDate.getTime() - new Date().getTime()) / (1000 * 60 * 60 * 24))
    : null

  if (loading) return <div className="text-center py-20 text-muted-foreground">Memuat...</div>
  if (error || !po) return <div className="text-center py-20 text-muted-foreground">Customer PO tidak ditemukan</div>

  return (
    <div className="space-y-6">
      <div className="flex items-center gap-4">
        <Button variant="ghost" size="icon" onClick={() => router.push("/dashboard/customer-po")}><ArrowLeft className="h-5 w-5" /></Button>
        <div><h1 className="text-3xl font-heading font-bold">Detail Customer PO</h1><p className="text-muted-foreground mt-1">{po.nomor}</p></div>
        <div className="ml-auto flex items-center gap-2">
          {po.status === 'draft' && (
            <>
              <Button onClick={() => handleStatusChange('confirmed')} disabled={statusLoading}>
                {statusLoading ? <Loader2 className="h-4 w-4 mr-2 animate-spin" /> : <CheckCircle className="h-4 w-4 mr-2" />}
                Konfirmasi
              </Button>
              <Button variant="destructive" onClick={() => handleStatusChange('cancelled')} disabled={statusLoading}>
                {statusLoading ? <Loader2 className="h-4 w-4 mr-2 animate-spin" /> : null}
                Batal
              </Button>
            </>
          )}
          {po.sales_order ? (
            <Button variant="default" size="sm" asChild>
              <Link href={`/dashboard/sales-order/${po.sales_order.id}`}>
                Lihat SO <ExternalLink className="h-4 w-4 ml-1" />
              </Link>
            </Button>
          ) : po.status === 'confirmed' ? (
            <Button variant="default" size="sm" onClick={async () => {
              try {
                const res = await apiFetch<{ salesOrder: { id: string; nomor: string } }>(`/api/v1/customer-po/${po.id}`, { method: 'PUT', body: JSON.stringify({ action: 'generate_so' }) })
                toast.success(`SO ${res.data.salesOrder.nomor} berhasil dibuat!`, {
                  action: { label: 'Lihat SO', onClick: () => router.push(`/dashboard/sales-order/${res.data.salesOrder.id}`) },
                })
                const refreshed = await apiFetch<CustomerPo>(`/api/v1/customer-po/${po.id}`)
                setPo(refreshed.data)
              } catch (err) {
                toast.error(err instanceof Error ? err.message : 'Gagal generate SO')
              }
            }}>
              Buat SO <ExternalLink className="h-4 w-4 ml-1" />
            </Button>
          ) : null}
        </div>
      </div>

      <Card>
        <CardContent className="pt-6">
          <div className="grid grid-cols-2 gap-6">
            <div>
              <p className="text-sm text-muted-foreground">Nomor</p>
              <p className="font-medium">{po.nomor}</p>
            </div>
            <div>
              <p className="text-sm text-muted-foreground">Status</p>
              <Badge variant={s[po.status]?.v ?? "outline"}>{s[po.status]?.label ?? po.status}</Badge>
            </div>
            <div>
              <p className="text-sm text-muted-foreground">Tanggal</p>
              <p className="font-medium">{new Date(po.tanggal).toLocaleDateString('id-ID', { day: '2-digit', month: 'long', year: 'numeric' })}</p>
            </div>
            <div>
              <p className="text-sm text-muted-foreground">Customer</p>
              <p className="font-medium">{po.customer?.nama} ({po.customer?.kode})</p>
            </div>
            <div>
              <p className="text-sm text-muted-foreground">PO Customer</p>
              <p className="font-medium">{po.nomor_po_customer ?? "-"}</p>
            </div>
            <div>
              <p className="text-sm text-muted-foreground">Terms of Payment</p>
              <p className="font-medium">{po.terms_of_payment ?? "-"}</p>
            </div>
            <div>
              <p className="text-sm text-muted-foreground">PIC Customer</p>
              <p className="font-medium">{po.customer_pic?.nama ?? "-"}</p>
              {po.customer_pic?.jabatan && <p className="text-xs text-muted-foreground">{po.customer_pic.jabatan}</p>}
            </div>
            <div>
              <p className="text-sm text-muted-foreground">Batas Kirim Barang</p>
              {dueDate ? (
                <div className="flex flex-col gap-1">
                  <p className="font-medium">
                    {dueDate.toLocaleDateString('id-ID', { day: '2-digit', month: 'long', year: 'numeric' })}
                  </p>
                  <p className="text-xs text-muted-foreground">{po.waktu_pengiriman} hari setelah PO Terbit</p>
                  {daysUntilDue != null && daysUntilDue < 0 ? (
                    <Badge variant="destructive" className="flex items-center gap-1 w-fit">
                      <AlertTriangle className="h-3 w-3" /> Terlambat {-daysUntilDue} hari
                    </Badge>
                  ) : daysUntilDue != null && daysUntilDue <= 1 ? (
                    <Badge variant="warning" className="flex items-center gap-1 w-fit">
                      <AlertTriangle className="h-3 w-3" /> H-{daysUntilDue}
                    </Badge>
                  ) : daysUntilDue != null && daysUntilDue > 1 ? (
                    <Badge variant="success" className="flex items-center gap-1 w-fit">
                      <CheckCircle2 className="h-3 w-3" /> H-{daysUntilDue}
                    </Badge>
                  ) : null}
                </div>
              ) : (
                <p className="font-medium">-</p>
              )}
            </div>
            <div>
              <p className="text-sm text-muted-foreground">Jatuh Tempo Pembayaran</p>
              <p className="font-medium text-xs">Dihitung setelah invoice hardcopy diterima customer</p>
            </div>
          </div>
          {po.terms_of_payment && po.terms_of_payment !== 'Cash' && (
            <div className="mt-4 text-sm bg-blue-50 border border-blue-200 rounded-md px-4 py-3 space-y-1">
              <p className="font-medium text-blue-800">Informasi TOP</p>
              <p className="text-blue-700">
                Jatuh tempo pembayaran Invoice adalah {(() => {
                  const match = po.terms_of_payment!.match(/\d+/)
                  return match ? Number(match[0]) : '—'
                })()} hari setelah hardcopy invoice diterima Customer.
              </p>
            </div>
          )}
          {po.terms_of_payment === 'Cash' && (
            <div className="mt-4 text-sm bg-blue-50 border border-blue-200 rounded-md px-4 py-3">
              <p className="font-medium text-blue-800">Informasi TOP</p>
              <p className="text-blue-700">Jatuh tempo pembayaran Invoice adalah Cash (lunas saat penerimaan invoice).</p>
            </div>
          )}
        </CardContent>
      </Card>

      {!!po.items?.length && (
        <Card>
          <CardContent className="pt-6">
            <h3 className="text-lg font-semibold mb-4 flex items-center gap-2"><FileText className="h-4 w-4" />Item Barang</h3>
            <Table>
              <TableHeader>
                <TableRow>
                  <TableHead className="w-14">Picture</TableHead>
                  <TableHead>Barang</TableHead>
                  <TableHead>Kode</TableHead>
                  <TableHead>Satuan</TableHead>
                  <TableHead className="text-right">Jumlah</TableHead>
                  <TableHead className="text-right">Harga</TableHead>
                  <TableHead className="text-right">Subtotal</TableHead>
                </TableRow>
              </TableHeader>
              <TableBody>
                {po.items.map((item) => (
                  <TableRow key={item.id}>
                    <TableCell>
                      {item.barang?.image_url
                        ? <img src={item.barang.image_url} alt={item.barang.nama} className="h-10 w-10 object-cover rounded" />
                        : <div className="h-10 w-10 rounded bg-muted flex items-center justify-center text-muted-foreground text-xs">-</div>
                      }
                    </TableCell>
                    <TableCell className="font-medium">{item.barang?.nama}</TableCell>
                    <TableCell className="text-muted-foreground">{item.barang?.kode}</TableCell>
                    <TableCell>{item.barang?.satuan}</TableCell>
                    <TableCell className="text-right">{item.jumlah}</TableCell>
                    <TableCell className="text-right">{item.harga_satuan?.toLocaleString("id-ID")}</TableCell>
                    <TableCell className="text-right">{(item.jumlah * item.harga_satuan).toLocaleString("id-ID")}</TableCell>
                  </TableRow>
                ))}
              </TableBody>
            </Table>
            <div className="mt-4 text-right font-bold text-lg">
              Total: {po.items.reduce((sum, i) => sum + i.jumlah * i.harga_satuan, 0).toLocaleString("id-ID")}
            </div>
          </CardContent>
        </Card>
      )}

      <Card>
        <CardContent className="pt-6">
          <h3 className="text-lg font-semibold mb-4">Lampiran</h3>
          <CompactFileUpload
            documents={documents}
            onUpload={handleUpload}
            onDelete={handleDeleteDocument}
            uploading={uploading}
          />
        </CardContent>
      </Card>
    </div>
  )
}
