"use client"
import { useState, useEffect } from 'react'
import { useRouter, useParams } from 'next/navigation'
import Link from 'next/link'
import { apiFetch } from '@/lib/api/client'
import { Button } from '@/components/ui/button'
import { Badge } from '@/components/ui/badge'
import { Card, CardContent } from '@/components/ui/card'
import { Table, TableHeader, TableBody, TableRow, TableHead, TableCell } from '@/components/ui/table'
import { ArrowLeft, FileText, ExternalLink, Loader2 } from 'lucide-react'
import { toast } from 'sonner'
import { SoDocuments } from '@/components/so-documents'

const STATUS_MAP: Record<string, { label: string; v: 'secondary' | 'warning' | 'success' | 'outline' | 'destructive' }> = {
  draft: { label: 'Draft', v: 'secondary' },
  confirmed: { label: 'Dikonfirmasi', v: 'warning' },
  processed: { label: 'Diproses', v: 'success' },
  delivered: { label: 'Dikirim', v: 'outline' },
  cancelled: { label: 'Dibatalkan', v: 'destructive' },
}

const QUICK_ACTIONS: Record<string, Array<{ status: string; label: string; variant?: 'default' | 'destructive' }>> = {
  draft: [
    { status: 'confirmed', label: 'Konfirmasi' },
    { status: 'cancelled', label: 'Batalkan', variant: 'destructive' },
  ],
  confirmed: [
    { status: 'processed', label: 'Proses' },
  ],
  processed: [
    { status: 'delivered', label: 'Kirim' },
  ],
  delivered: [],
  cancelled: [],
}

export default function SalesOrderDetailPage() {
  const router = useRouter()
  const params = useParams()
  const id = params.id as string
  const [so, setSo] = useState<Record<string, unknown> | null>(null)
  const [items, setItems] = useState<Array<Record<string, unknown>>>([])
  const [doDoc, setDoDoc] = useState<Record<string, unknown> | null>(null)
  const [loading, setLoading] = useState(true)
  const [actionLoading, setActionLoading] = useState<string | null>(null)
  const [fetchKey, setFetchKey] = useState(0)

  useEffect(() => {
    let cancelled = false
    apiFetch<Record<string, unknown>>(`/api/v1/sales-order/${id}`)
      .then((r) => {
        if (cancelled) return
        const d = r.data
        setSo(d)
        setItems((d.items as Array<Record<string, unknown>>) ?? [])
        setDoDoc((d.delivery_order as Record<string, unknown>) ?? null)
        setLoading(false)
      })
      .catch(() => {
        if (cancelled) return
        toast.error('Gagal memuat data')
        router.push('/dashboard/sales-order')
      })
    return () => { cancelled = true }
  }, [id, fetchKey])

  const refresh = () => { setLoading(true); setFetchKey(k => k + 1) }

  const toggleActive = async () => {
    const newVal = !(so?.is_active as boolean)
    setActionLoading('is_active')
    try {
      await apiFetch(`/api/v1/sales-order/${id}`, { method: 'PUT', body: JSON.stringify({ is_active: newVal }) })
      toast.success(newVal ? 'SO diaktifkan' : 'SO dinonaktifkan')
      refresh()
    } catch (err) {
      toast.error(err instanceof Error ? err.message : 'Gagal')
    } finally {
      setActionLoading(null)
    }
  }

  const handleAction = async (newStatus: string) => {
    setActionLoading(newStatus)
    try {
      const res = await apiFetch<{ autoGenerated?: { id: string; nomor: string; type: string } }>(
        `/api/v1/sales-order/${id}`,
        { method: 'PUT', body: JSON.stringify({ status: newStatus }) }
      )
      const autoGenerated = res.data?.autoGenerated
      if (autoGenerated) {
        toast.success(`SO ${STATUS_MAP[newStatus]?.label ?? newStatus}!`, {
          description: `Delivery Order ${autoGenerated.nomor} otomatis dibuat`,
          action: { label: 'Lihat DO', onClick: () => router.push(`/dashboard/delivery-order/${autoGenerated.id}`) },
        })
      } else {
        toast.success(`SO ${STATUS_MAP[newStatus]?.label ?? newStatus}!`)
      }
      refresh()
    } catch (err) {
      toast.error(err instanceof Error ? err.message : 'Gagal update status')
    } finally {
      setActionLoading(null)
    }
  }

  if (loading) return <div className="flex justify-center py-20"><Loader2 className="h-6 w-6 animate-spin" /></div>
  if (!so) return <div className="text-center py-20 text-muted-foreground">Sales Order tidak ditemukan</div>

  const statusKey = (so.status as string) ?? 'draft'
  const statusConfig = STATUS_MAP[statusKey] ?? { label: statusKey, v: 'outline' as const }
  const actions = QUICK_ACTIONS[statusKey] ?? []
  const customerPo = so.customer_po as Record<string, unknown> | null
  const customer = customerPo?.customer as Record<string, unknown> | null
  const picCustomer = customerPo?.pic_customer as Record<string, unknown> | null

  const total = items.reduce((sum: number, i: Record<string, unknown>) => {
    return sum + (i.jumlah as number) * (i.harga_satuan as number)
  }, 0)

  const estimasiKirim = so.waktu_pengiriman
    ? new Date(new Date(so.tanggal as string).getTime() + (so.waktu_pengiriman as number) * 86400000)
    : null

  return (
    <div className="space-y-6">
      <div className="flex items-center gap-4">
        <Button variant="ghost" size="icon" asChild>
          <Link href="/dashboard/sales-order"><ArrowLeft className="h-5 w-5" /></Link>
        </Button>
        <div>
          <h1 className="text-3xl font-heading font-bold">Detail Sales Order</h1>
          <p className="text-muted-foreground mt-1">{so.nomor as string}</p>
        </div>
        <div className="ml-auto flex items-center gap-2">
          {actions.map((action) => (
            <Button
              key={action.status}
              variant={action.variant ?? 'default'}
              size="sm"
              onClick={() => handleAction(action.status)}
              disabled={actionLoading === action.status}
            >
              {actionLoading === action.status ? <Loader2 className="h-4 w-4 mr-1 animate-spin" /> : null}
              {action.label}
            </Button>
          ))}
          {doDoc ? (
            <Button variant="outline" size="sm" asChild>
              <Link href={`/dashboard/delivery-order/${doDoc.id as string}`}>
                Lihat DO <ExternalLink className="h-4 w-4 ml-1" />
              </Link>
            </Button>
          ) : null}
          <Button variant="outline" size="sm" onClick={toggleActive} disabled={actionLoading === 'is_active'}>
            {actionLoading === 'is_active' ? <Loader2 className="h-4 w-4 animate-spin" /> : so.is_active ? 'Nonaktifkan' : 'Aktifkan'}
          </Button>
        </div>
      </div>

      <div className="grid grid-cols-2 gap-6">
        <Card>
          <CardContent className="pt-6 space-y-4">
            <h3 className="text-sm font-semibold text-muted-foreground uppercase tracking-wider">Informasi SO</h3>
            <div className="grid grid-cols-2 gap-4">
              <div>
                <p className="text-sm text-muted-foreground">Nomor</p>
                <p className="font-medium">{so.nomor as string}</p>
              </div>
              <div>
                <p className="text-sm text-muted-foreground">Status</p>
                <div className="flex items-center gap-2">
                  <Badge variant={statusConfig.v}>{statusConfig.label}</Badge>
                  <Badge variant={so.is_active ? 'default' : 'secondary'} className="text-xs">
                    {so.is_active ? 'Aktif' : 'Nonaktif'}
                  </Badge>
                </div>
              </div>
              <div>
                <p className="text-sm text-muted-foreground">Tanggal</p>
                <p className="font-medium">{new Date(so.tanggal as string).toLocaleDateString('id-ID')}</p>
              </div>
              {estimasiKirim ? (
                <div>
                  <p className="text-sm text-muted-foreground">Estimasi Kirim</p>
                  <p className="font-medium">{estimasiKirim.toLocaleDateString('id-ID')}</p>
                  <p className="text-xs text-muted-foreground">{so.waktu_pengiriman as string} hari setelah SO</p>
                </div>
              ) : null}
              <div>
                <p className="text-sm text-muted-foreground">Referensi PO</p>
                <p className="font-medium">{customerPo?.nomor as string ?? '-'}</p>
              </div>
              <div>
                <p className="text-sm text-muted-foreground">Referensi DI</p>
                <p className="font-medium">{so.di_id ? (so.di_id as string).slice(0, 8) + '...' : '-'}</p>
              </div>
            </div>
          </CardContent>
        </Card>

        <Card>
          <CardContent className="pt-6 space-y-4">
            <h3 className="text-sm font-semibold text-muted-foreground uppercase tracking-wider">Informasi Customer</h3>
            <div className="grid grid-cols-2 gap-4">
              <div>
                <p className="text-sm text-muted-foreground">Nama Customer</p>
                <p className="font-medium">{customer?.nama as string ?? '-'}</p>
              </div>
              <div>
                <p className="text-sm text-muted-foreground">Kode Customer</p>
                <p className="font-medium">{customer?.kode as string ?? '-'}</p>
              </div>
              <div>
                <p className="text-sm text-muted-foreground">PIC</p>
                <p className="font-medium">{picCustomer?.nama as string ?? '-'}</p>
              </div>
              <div>
                <p className="text-sm text-muted-foreground">Telepon PIC</p>
                <p className="font-medium">{picCustomer?.telepon as string ?? '-'}</p>
              </div>
              {customerPo?.waktu_pengiriman ? (
                <div>
                  <p className="text-sm text-muted-foreground">Waktu Pengiriman (PO)</p>
                  <p className="font-medium">{customerPo.waktu_pengiriman as string} hari</p>
                </div>
              ) : null}
            </div>
          </CardContent>
        </Card>
      </div>

      {items.length > 0 && (
        <Card>
          <CardContent className="pt-6">
            <h3 className="text-lg font-semibold mb-4 flex items-center gap-2">
              <FileText className="h-4 w-4" />Item Barang
            </h3>
            <Table>
              <TableHeader>
                <TableRow>
                  <TableHead>Barang</TableHead>
                  <TableHead>Kode</TableHead>
                  <TableHead className="text-right">Jumlah</TableHead>
                  <TableHead>Satuan</TableHead>
                  <TableHead className="text-right">Harga</TableHead>
                  <TableHead className="text-right">Subtotal</TableHead>
                </TableRow>
              </TableHeader>
              <TableBody>
                {items.map((item: Record<string, unknown>) => {
                  const barang = item.barang as Record<string, unknown> ?? {}
                  return (
                    <TableRow key={item.id as string}>
                      <TableCell className="font-medium">{barang.nama as string}</TableCell>
                      <TableCell className="text-muted-foreground">{barang.kode as string}</TableCell>
                      <TableCell className="text-right">{item.jumlah as number}</TableCell>
                      <TableCell>{barang.satuan as string}</TableCell>
                      <TableCell className="text-right">{(item.harga_satuan as number)?.toLocaleString('id-ID')}</TableCell>
                      <TableCell className="text-right">{((item.jumlah as number) * (item.harga_satuan as number)).toLocaleString('id-ID')}</TableCell>
                    </TableRow>
                  )
                })}
              </TableBody>
            </Table>
            <div className="mt-4 text-right font-bold text-lg">
              Total: {total.toLocaleString('id-ID')}
            </div>
          </CardContent>
        </Card>
      )}

      <Card>
        <CardContent className="pt-6">
          <h3 className="text-lg font-semibold mb-4">Lampiran</h3>
          <SoDocuments soId={id} />
        </CardContent>
      </Card>
    </div>
  )
}
