import { NextRequest, NextResponse } from 'next/server'
import { supabaseAdmin } from '@/lib/api/supabase-server'
import { verifyAuth } from '@/lib/api/auth'
import { badRequest, notFound, internalError } from '@/lib/api/errors'
import { generateSOFromPO } from '@/lib/auto-sales'
import { createBarangFromRfqItem, getUnmappedRfqItems } from '@/lib/utils/barang-auto-create'
import { sendWhatsapp } from '@/lib/utils/whatsapp'

export async function GET(_request: NextRequest, { params }: { params: Promise<{ id: string }> }) {
  const auth = await verifyAuth(_request); if (auth.error) return auth.error
  const { id } = await params
  const { data: po, error } = await supabaseAdmin.from('customer_po').select('*, customer!customer_id(nama, kode), customer_pic!pic_customer_id(nama, jabatan, no_hp), quotation!quotation_id(nomor)').eq('id', id).single()
  if (error) return internalError(error)
  if (!po) return notFound('PO tidak ditemukan')
  const { data: items } = await supabaseAdmin.from('customer_po_item').select('*, barang!barang_id(nama, kode, satuan, image_url)').eq('customer_po_id', id)
  const { data: so } = await supabaseAdmin.from('sales_order').select('id, nomor, status').eq('customer_po_id', id).maybeSingle()
  return NextResponse.json({ data: { ...po, items: items ?? [], sales_order: so ?? null } })
}

const PO_ALLOWED_TRANSITIONS: Record<string, string[]> = {
  draft: ['confirmed', 'cancelled'],
  confirmed: [],
  cancelled: [],
}

function isValidPoTransition(from: string, to: string): boolean {
  if (from === to) return true
  return PO_ALLOWED_TRANSITIONS[from]?.includes(to) ?? false
}

export async function PUT(request: NextRequest, { params }: { params: Promise<{ id: string }> }) {
  const auth = await verifyAuth(request)
  if (auth.error) return auth.error
  const { id } = await params
  const body = await request.json().catch(() => null)
  if (!body) return badRequest('Invalid JSON body')

  const { data: old } = await supabaseAdmin.from('customer_po').select('status, quotation_id').eq('id', id).single()
  if (!old) return notFound('PO tidak ditemukan')

  if (body.status && !isValidPoTransition(old.status, body.status)) {
    return badRequest(`Status PO tidak bisa diubah dari '${old.status}' ke '${body.status}'`)
  }

  const upd: Record<string, unknown> = {}
  if (body.status) upd.status = body.status
  if (body.nomor_po_customer !== undefined) upd.nomor_po_customer = body.nomor_po_customer
  if (body.terms_of_payment !== undefined) upd.terms_of_payment = body.terms_of_payment
  if (body.keterangan !== undefined) upd.keterangan = body.keterangan
  if (body.waktu_pengiriman !== undefined) upd.waktu_pengiriman = body.waktu_pengiriman
  if (body.pic_customer_id !== undefined) upd.pic_customer_id = body.pic_customer_id || null
  upd.updated_at = new Date().toISOString()

  const { data, error } = await supabaseAdmin.from('customer_po').update(upd).eq('id', id).select().single()
  if (error) return internalError(error)
  if (!data) return notFound('PO tidak ditemukan')

  if (body.items) {
    await supabaseAdmin.from('customer_po_item').delete().eq('customer_po_id', id)
    const now = new Date().toISOString()
    const items = body.items.map((item: { barang_id: string; jumlah: number; harga_satuan: number; keterangan?: string; image_url?: string | null }) => ({
      customer_po_id: id, barang_id: item.barang_id, jumlah: item.jumlah,
      harga_satuan: item.harga_satuan, keterangan: item.keterangan ?? null, created_at: now, updated_at: now,
    }))
    const { error: itemsError } = await supabaseAdmin.from('customer_po_item').insert(items)
    if (itemsError) return internalError(itemsError)

    for (const item of body.items) {
      if (item.image_url) {
        await supabaseAdmin.from('barang').update({ image_url: item.image_url }).eq('id', item.barang_id).is('image_url', null)
      }
    }
  }

  let autoGenerated = null
  if (body.status === 'confirmed' && old?.status !== 'confirmed') {
    // Auto-close quotation if PO references one
    if (old?.quotation_id) {
      await supabaseAdmin
        .from('quotation')
        .update({ status: 'closed', updated_at: new Date().toISOString() })
        .eq('id', old.quotation_id)
    }
    const result = await generateSOFromPO(id)
    if (result.success) autoGenerated = result.data

    // Send WhatsApp notification to PIC Customer
    const { data: poWithCustomer } = await supabaseAdmin.from('customer_po').select('*, customer!customer_id(nama, pic_customer)').eq('id', id).single()
    if (poWithCustomer?.customer) {
      const { data: pics } = await supabaseAdmin.from('customer_pic').select('no_hp, nama').eq('customer_id', poWithCustomer.customer_id).eq('is_active', true).limit(1)
      const pic = pics?.[0]
      if (pic?.no_hp) {
        const msg = `Kepada Yth. ${pic.nama},\n\nPO/DI No. *${poWithCustomer.nomor}* dari ${poWithCustomer.customer.nama} telah DEAL dan dikonfirmasi.\n\nTerima kasih atas kerjasamanya.\n\n- ERP RRI`
        await sendWhatsapp(pic.no_hp, msg, auth.user?.id)
      }
    }

    // Auto-create master barang from unmapped RFQ items
    if (body.barang_auto_create && Array.isArray(body.barang_auto_create) && body.barang_auto_create.length > 0) {
      const unmappedItems = await getUnmappedRfqItems(id)
      const created: Array<{ nama: string; kode: string }> = []
      for (const cfg of body.barang_auto_create) {
        const item = unmappedItems.find((u: { id: string }) => u.id === cfg.item_id)
        if (!item) continue
        const newBarang = await createBarangFromRfqItem(
          cfg.nama_barang || item.nama_barang || '',
          cfg.satuan || item.satuan,
          cfg.kategori_id,
          item.image_url,
          item.harga_satuan,
        )
        created.push({ nama: newBarang.nama, kode: newBarang.kode })
        await supabaseAdmin.from('rfq_customer_item').update({ barang_id: newBarang.id }).eq('id', item.id)
      }
      if (created.length > 0) {
        const names = created.map((c: { nama: string; kode: string }) => c.nama).join(', ')
        console.log('Barang auto-created from RFQ:', names)
      }
    }
  }

  return NextResponse.json({ data: { ...data, autoGenerated } })
}

export async function DELETE(request: NextRequest, { params }: { params: Promise<{ id: string }> }) {
  const auth = await verifyAuth(request)
  if (auth.error) return auth.error
  const { id } = await params
  await supabaseAdmin.from('customer_po_item').delete().eq('customer_po_id', id)
  const { error } = await supabaseAdmin.from('customer_po').delete().eq('id', id)
  if (error) return internalError(error)
  return new NextResponse(null, { status: 204 })
}
