"use client"

import { useState, useEffect } from "react"
import { useRouter, usePathname } from "next/navigation"
import { apiFetch } from "@/lib/api/client"
import { Button } from "@/components/ui/button"
import { Badge } from "@/components/ui/badge"
import { Card, CardContent } from "@/components/ui/card"
import { Table, TableHeader, TableBody, TableRow, TableHead, TableCell } from "@/components/ui/table"
import Link from "next/link"
import { ArrowLeft, FileText, CheckCircle, Loader2, ExternalLink } from "lucide-react"
import { FileUpload, type DocumentFile } from "@/components/file-upload"
import { toast } from "sonner"

const s: Record<string, { label: string; v: "secondary" | "warning" | "success" | "outline" }> = {
  draft: { label: "Draft", v: "secondary" },
  confirmed: { label: "Dikonfirmasi", v: "success" },
  cancelled: { label: "Batal", v: "outline" },
}

interface Di {
  id: string
  nomor: string
  customer_id: string
  kontrak_id: string | null
  pic_customer_id: string | null
  tanggal: string
  status: string
  keterangan: string | null
  customer: { nama: string; kode: string } | null
  customer_pic: { nama: string; jabatan: string | null; no_hp: string | null } | null
  kontrak: { nama: string; nomor_kontrak: string | null } | null
  sales_order: { id: string; nomor: string; status: string } | null
  items: Array<{
    id: string
    jumlah: number
    harga_satuan: number
    barang: { nama: string; kode: string; satuan: string } | null
  }>
}

export default function DiDetailPage() {
  const router = useRouter()
  const pathname = usePathname()
  const id = pathname.split("/").pop()
  const [di, setDi] = useState<Di | null>(null)
  const [loading, setLoading] = useState(true)
  const [error, setError] = useState<string | null>(null)
  const [documents, setDocuments] = useState<DocumentFile[]>([])
  const [uploading, setUploading] = useState(false)
  const [statusLoading, setStatusLoading] = useState(false)

  const handleStatusChange = async (newStatus: string) => {
    if (!id) return
    setStatusLoading(true)
    try {
      const putRes = await apiFetch<{ autoGenerated?: { id: string; nomor: string; type: string } }>(`/api/v1/di/${id}`, {
        method: 'PUT',
        body: JSON.stringify({ status: newStatus }),
      })
      if (putRes.data?.autoGenerated) {
        toast.success(`DI dikonfirmasi! ${putRes.data.autoGenerated.nomor} telah dibuat.`)
      } else {
        toast.success(`DI berhasil ${newStatus === 'confirmed' ? 'dikonfirmasi' : 'dibatalkan'}!`)
      }
      const res = await apiFetch<Di>(`/api/v1/di/${id}`)
      setDi(res.data)
    } catch (err) {
      toast.error(err instanceof Error ? err.message : 'Gagal mengubah status')
    } finally {
      setStatusLoading(false)
    }
  }

  useEffect(() => {
    if (!id) return
    Promise.all([
      apiFetch<Di>(`/api/v1/di/${id}`),
      apiFetch<DocumentFile[]>(`/api/v1/di/${id}/documents`),
    ]).then(([diRes, docRes]) => {
      setDi(diRes.data)
      setDocuments(docRes.data ?? [])
      setLoading(false)
    }).catch((err) => {
      setError(err.message)
      setLoading(false)
    })
  }, [id])

  const handleUpload = async (file: File) => {
    if (!id) return
    setUploading(true)
    try {
      const formData = new FormData()
      formData.append("file", file)
      const { apiFetchFormData } = await import("@/lib/api/client")
      const r = await apiFetchFormData(`/api/v1/di/${id}/documents`, formData)
      setDocuments((prev) => [r.data as DocumentFile, ...prev].filter(Boolean))
      toast.success("File berhasil diupload")
    } catch (err) {
      toast.error(err instanceof Error ? err.message : "Gagal upload file")
    } finally {
      setUploading(false)
    }
  }

  const handleDeleteDocument = async (docId: string) => {
    if (!id) return
    try {
      await apiFetch(`/api/v1/di/${id}/documents?docId=${docId}`, { method: "DELETE" })
      setDocuments((prev) => prev.filter((d) => d.id !== docId))
      toast.success("File berhasil dihapus")
    } catch (err) {
      toast.error(err instanceof Error ? err.message : "Gagal hapus file")
    }
  }

  if (loading) return <div className="text-center py-20 text-muted-foreground">Memuat...</div>
  if (error || !di) return <div className="text-center py-20 text-muted-foreground">DI tidak ditemukan</div>

  return (
    <div className="space-y-6">
      <div className="flex items-center gap-4">
        <Button variant="ghost" size="icon" onClick={() => router.push("/dashboard/di")}><ArrowLeft className="h-5 w-5" /></Button>
        <div><h1 className="text-3xl font-heading font-bold">Detail DI</h1><p className="text-muted-foreground mt-1">{di.nomor}</p></div>
        <div className="ml-auto flex items-center gap-2">
          {di.status === 'draft' && (
            <>
              <Button onClick={() => handleStatusChange('confirmed')} disabled={statusLoading}>
                {statusLoading ? <Loader2 className="h-4 w-4 mr-2 animate-spin" /> : <CheckCircle className="h-4 w-4 mr-2" />}
                Setujui
              </Button>
              <Button variant="destructive" onClick={() => handleStatusChange('cancelled')} disabled={statusLoading}>
                {statusLoading ? <Loader2 className="h-4 w-4 mr-2 animate-spin" /> : null}
                Batal
              </Button>
            </>
          )}
          {di.sales_order ? (
            <Button variant="default" size="sm" asChild>
              <Link href={`/dashboard/sales-order/${di.sales_order.id}`}>
                Lihat SO <ExternalLink className="h-4 w-4 ml-1" />
              </Link>
            </Button>
          ) : di.status === 'confirmed' ? (
            <Button variant="default" size="sm" onClick={async () => {
              try {
                const res = await apiFetch<{ salesOrder: { id: string; nomor: string } }>(`/api/v1/di/${di.id}`, { method: 'PUT', body: JSON.stringify({ action: 'generate_so' }) })
                toast.success(`SO ${res.data.salesOrder.nomor} berhasil dibuat!`, {
                  action: { label: 'Lihat SO', onClick: () => router.push(`/dashboard/sales-order/${res.data.salesOrder.id}`) },
                })
                const refreshed = await apiFetch<Di>(`/api/v1/di/${di.id}`)
                setDi(refreshed.data)
              } catch (err) {
                toast.error(err instanceof Error ? err.message : 'Gagal generate SO')
              }
            }}>
              Buat SO <ExternalLink className="h-4 w-4 ml-1" />
            </Button>
          ) : null}
        </div>
      </div>

      <Card>
        <CardContent className="pt-6">
          <div className="grid grid-cols-2 gap-6">
            <div>
              <p className="text-sm text-muted-foreground">Nomor</p>
              <p className="font-medium">{di.nomor}</p>
            </div>
            <div>
              <p className="text-sm text-muted-foreground">Status</p>
              <Badge variant={s[di.status]?.v ?? "outline"}>{s[di.status]?.label ?? di.status}</Badge>
            </div>
            <div>
              <p className="text-sm text-muted-foreground">Tanggal</p>
              <p className="font-medium">{new Date(di.tanggal).toLocaleDateString('id-ID', { day: '2-digit', month: 'long', year: 'numeric' })}</p>
            </div>
            <div>
              <p className="text-sm text-muted-foreground">Customer</p>
              <p className="font-medium">{di.customer?.nama} ({di.customer?.kode})</p>
            </div>
            <div>
              <p className="text-sm text-muted-foreground">PIC Customer</p>
              <p className="font-medium">{di.customer_pic?.nama ?? "-"}</p>
              {di.customer_pic?.jabatan && <p className="text-xs text-muted-foreground">{di.customer_pic.jabatan}</p>}
            </div>
            <div>
              <p className="text-sm text-muted-foreground">Kontrak</p>
              <p className="font-medium">{di.kontrak?.nama ? `${di.kontrak.nama}${di.kontrak.nomor_kontrak ? ` (${di.kontrak.nomor_kontrak})` : ''}` : "-"}</p>
            </div>
            <div className="col-span-2">
              <p className="text-sm text-muted-foreground">Keterangan</p>
              <p className="font-medium">{di.keterangan ?? "-"}</p>
            </div>
          </div>
        </CardContent>
      </Card>

      {!!di.items?.length && (
        <Card>
          <CardContent className="pt-6">
            <h3 className="text-lg font-semibold mb-4 flex items-center gap-2"><FileText className="h-4 w-4" />Item Barang</h3>
            <Table>
              <TableHeader>
                <TableRow>
                  <TableHead>Barang</TableHead>
                  <TableHead>Kode</TableHead>
                  <TableHead>Satuan</TableHead>
                  <TableHead className="text-right">Jumlah</TableHead>
                  <TableHead className="text-right">Harga</TableHead>
                  <TableHead className="text-right">Subtotal</TableHead>
                </TableRow>
              </TableHeader>
              <TableBody>
                {di.items.map((item) => (
                  <TableRow key={item.id}>
                    <TableCell className="font-medium">{item.barang?.nama}</TableCell>
                    <TableCell className="text-muted-foreground">{item.barang?.kode}</TableCell>
                    <TableCell>{item.barang?.satuan}</TableCell>
                    <TableCell className="text-right">{item.jumlah}</TableCell>
                    <TableCell className="text-right">{item.harga_satuan?.toLocaleString("id-ID")}</TableCell>
                    <TableCell className="text-right">{(item.jumlah * item.harga_satuan).toLocaleString("id-ID")}</TableCell>
                  </TableRow>
                ))}
              </TableBody>
            </Table>
            <div className="mt-4 text-right font-bold text-lg">
              Total: {di.items.reduce((sum, i) => sum + i.jumlah * i.harga_satuan, 0).toLocaleString("id-ID")}
            </div>
          </CardContent>
        </Card>
      )}

      <Card>
        <CardContent className="pt-6">
          <h3 className="text-lg font-semibold mb-4">Lampiran</h3>
          <FileUpload
            documents={documents}
            onUpload={handleUpload}
            onDelete={handleDeleteDocument}
            uploading={uploading}
          />
        </CardContent>
      </Card>
    </div>
  )
}
