import { NextRequest, NextResponse } from 'next/server'
import { supabaseAdmin } from '@/lib/api/supabase-server'
import { verifyAuth } from '@/lib/api/auth'
import { badRequest, notFound, internalError } from '@/lib/api/errors'
import { generateSOFromDI } from '@/lib/auto-sales'
import { sendWhatsapp } from '@/lib/utils/whatsapp'

export async function GET(_request: NextRequest, { params }: { params: Promise<{ id: string }> }) {
  const auth = await verifyAuth(_request); if (auth.error) return auth.error
  const { id } = await params
  const { data: di, error } = await supabaseAdmin
    .from('di')
    .select('*, customer!customer_id(nama, kode), kontrak!kontrak_id(nama, nomor_kontrak)')
    .eq('id', id).single()
  if (error) return internalError(error)
  if (!di) return notFound('DI tidak ditemukan')

  let picData = null
  if (di.pic_customer_id) {
    const { data: pic } = await supabaseAdmin.from('customer_pic').select('nama, jabatan, no_hp').eq('id', di.pic_customer_id).single()
    if (pic) picData = pic
  }

  const { data: items } = await supabaseAdmin.from('di_item').select('*, barang!barang_id(nama, kode, satuan)').eq('di_id', id)
  const { data: so } = await supabaseAdmin.from('sales_order').select('id, nomor, status').eq('di_id', id).maybeSingle()
  return NextResponse.json({ data: { ...di, customer_pic: picData, items: items ?? [], sales_order: so ?? null } })
}

const DI_ALLOWED_TRANSITIONS: Record<string, string[]> = {
  draft: ['confirmed', 'cancelled'],
  confirmed: [],
  cancelled: [],
}

function isValidDiTransition(from: string, to: string): boolean {
  if (from === to) return true
  return DI_ALLOWED_TRANSITIONS[from]?.includes(to) ?? false
}

export async function PUT(request: NextRequest, { params }: { params: Promise<{ id: string }> }) {
  const auth = await verifyAuth(request)
  if (auth.error) return auth.error
  const { id } = await params
  const body = await request.json().catch(() => null)
  if (!body) return badRequest('Invalid JSON body')

  const { data: old } = await supabaseAdmin.from('di').select('status').eq('id', id).single()
  if (!old) return notFound('DI tidak ditemukan')

  if (body.status && !isValidDiTransition(old.status, body.status)) {
    return badRequest(`Status DI tidak bisa diubah dari '${old.status}' ke '${body.status}'`)
  }

  const upd: Record<string, unknown> = {}
  if (body.status) upd.status = body.status
  if (body.keterangan !== undefined) upd.keterangan = body.keterangan
  if (body.pic_customer_id !== undefined) upd.pic_customer_id = body.pic_customer_id || null
  if (body.kontrak_id !== undefined) upd.kontrak_id = body.kontrak_id || null
  if (body.tanggal !== undefined) upd.tanggal = body.tanggal
  if (body.customer_id !== undefined) upd.customer_id = body.customer_id
  if (body.nomor_di_customer !== undefined) upd.nomor_di_customer = body.nomor_di_customer || null
  if (body.terms_of_payment !== undefined) upd.terms_of_payment = body.terms_of_payment || null
  if (body.waktu_pengiriman !== undefined) upd.waktu_pengiriman = body.waktu_pengiriman || null
  upd.updated_at = new Date().toISOString()

  const { data, error } = await supabaseAdmin.from('di').update(upd).eq('id', id).select().single()
  if (error) return internalError(error)
  if (!data) return notFound('DI tidak ditemukan')

  if (body.items) {
    await supabaseAdmin.from('di_item').delete().eq('di_id', id)
    const now = new Date().toISOString()
    const items = body.items.map((item: { barang_id: string; jumlah: number; harga_satuan: number; keterangan?: string }) => ({
      di_id: id, barang_id: item.barang_id, jumlah: item.jumlah,
      harga_satuan: item.harga_satuan ?? 0,
      keterangan: item.keterangan ?? null, created_at: now, updated_at: now,
    }))
    const { error: itemsError } = await supabaseAdmin.from('di_item').insert(items)
    if (itemsError) return internalError(itemsError)
  }

  let autoGenerated = null
  if (body.status === 'confirmed' && old?.status !== 'confirmed') {
    const result = await generateSOFromDI(id)
    if (result.success) autoGenerated = result.data

    const { data: diWithCustomer } = await supabaseAdmin.from('di').select('*, customer!customer_id(nama)').eq('id', id).single()
    if (diWithCustomer?.customer) {
      const { data: pics } = await supabaseAdmin.from('customer_pic').select('no_hp, nama').eq('customer_id', diWithCustomer.customer_id).eq('is_active', true).limit(1)
      const pic = pics?.[0]
      if (pic?.no_hp) {
        const msg = `Kepada Yth. ${pic.nama},\n\nDI No. *${diWithCustomer.nomor}* dari ${diWithCustomer.customer.nama} telah dikonfirmasi dan SO telah dibuat.\n\nTerima kasih atas kerjasamanya.\n\n- ERP RRI`
        await sendWhatsapp(pic.no_hp, msg, auth.user?.id)
      }
    }
  }

  return NextResponse.json({ data: { ...data, autoGenerated } })
}

export async function DELETE(request: NextRequest, { params }: { params: Promise<{ id: string }> }) {
  const auth = await verifyAuth(request)
  if (auth.error) return auth.error
  const { id } = await params
  await supabaseAdmin.from('di_item').delete().eq('di_id', id)
  const { error } = await supabaseAdmin.from('di').delete().eq('id', id)
  if (error) return internalError(error)
  return new NextResponse(null, { status: 204 })
}
